name: animated_accordion
description: A Flutter package for creating animated expandable accordion-style widgets with multiple animation options.
version: 1.0.0
homepage: https://github.com/mhmetglrq/animated_accordion
repository: https://github.com/mhmetglrq/animated_accordion
documentation: https://github.com/mhmetglrq/animated_accordion/wiki
environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# Optional: Add any additional dependencies like lints, build tools, etc.

flutter:
  uses-material-design: true

# Optional: Additional information
authors:
  - Mehmet GÃ¼ler <mhmetglr.q@gmail.com>
